apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-systems
  description: A collection of all Backstage example systems
spec:
  targets:
    - ./systems/campus-portal-system.yaml
    - ./systems/fbh-portal-system.yaml
    - ./systems/hisc-website-system.yaml
    #- ./systems/gurugram-website-system.yaml