apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
  description: The acme-corp organization
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: ACME Corp
    email: ramesh.pandi@heartfulness.org
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./ba-team.yaml
    - ./devops-aws-team.yaml
    - ./devops-gcp-team.yaml
    - ./managar-team.yaml
    - ./product-owner-team.yaml
    - ./qa-team.yaml
    - ./react-nextjs-team.yaml    
    - ./php-team.yaml
    - ./java-team.yaml