apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: qa-team
  description: QA Team
spec:
  type: team
  profile:
    displayName: Manikandan Sekar
    email: manikandan.sekar@volunteer.heartfulness.org
    picture: https://avatars.dicebear.com/api/identicon/team-c@example.com.svg?background=%23fff&margin=25
  parent: boxoffice
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bonagiri.rakesh
spec:
  profile:
    displayName: Bonagiri Rakesh
    email: bonagiri.rakesh@volunteer.heartfulness.org
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [qa-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: saivara.prasad
spec:
  profile:
    displayName: Saivara Prasad
    email: saivara.prasad@volunteer.heartfulness.org
    picture: https://avatars.dicebear.com/api/avataaars/frank-tiernan@example.com.svg?background=%23fff
  memberOf: [qa-team]
