apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: testing-template_!
  title: Testing Template 1
  description: Create a Wesbite Template
  tags:
    - recommended
    - react
spec:
  owner: rameshswe@gmail.com
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
  output:
    links:
      - title: Created Successfully
      
