apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: gurugram-components
  description: A collection of all Backstage example components
spec:
  targets:
    - ./components/gurugram/production/www-gurugram-component.yaml
   
    
