apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: campus-storage-bucket
  description: Stores Campus details
spec:
  type: Storage Bucket
  owner: devops-team-group
  system: campus-portal