apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devops-aws-team
  description: Devops AWS Team
spec:
  type: team
  profile:
    displayName: Vinodh
    email: vinodh.elangovan@volunteer.heartfulness.org
    picture: https://avatars.dicebear.com/api/identicon/team-c@example.com.svg?background=%23fff&margin=25
  parent: boxoffice
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sairam.regunta
spec:
  profile:
    displayName: Sairam Regunta
    email: sairam.regunta@volunteer.heartfulness.org
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [devops-aws-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mohan.raj
spec:
  profile:
    displayName: Mohan Raj
    email: mohan.raj@volunteer.heartfulness.org
    picture: https://avatars.dicebear.com/api/avataaars/frank-tiernan@example.com.svg?background=%23fff
  memberOf: [devops-aws-team]
