apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: php-team
  description: PHP development Team
spec:
  type: team
  profile:
    displayName: Arun Kurusev
    email: arunkurusev@volunteer.heartfulness.org
    picture: https://avatars.dicebear.com/api/identicon/team-b@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: arunkurusev
spec:
  profile:
    displayName: arunkurusev
    email: arunkurusev@volunteer.heartfulness.org
    picture: https://avatars.dicebear.com/api/avataaars/amelia-park@example.com.svg?background=%23fff
  memberOf: [php-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: hemanth.narra
spec:
  profile:
    displayName: Hemanth Reddy Narra
    email:  hemanth.narra@volunteer.heartfulness.org
    picture: https://avatars.dicebear.com/api/avataaars/amelia-park@example.com.svg?background=%23fff
  memberOf: [php-team]
