apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: www-gurugram
  description: Gurugram main website
  links:
    - url: https://heartfulness.org/meditation-center-in-gurugram/
      title: Home page
      icon: dashboard
  tags:
    - gatsby
spec:
  type: website
  lifecycle: production
  owner: react-nextjs-team
  system: gurugram-website
  consumesApis: ['component:google-sheet-lookup']