apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: srcm-login-component
  description: SRCM Login component
  tags:
    - nextjs
spec:
  type: library
  lifecycle: production
  owner: react-nextjs-team
  system: campus-portal