apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: Portal
  description: Everything related to Portal
  links:
    - url: https://campus.heartfulness.org/
      title: Domain Readme
    - url: https://campus.heartfulness.org/
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: devops-team-group